NORTH = 'North'
EAST = 'East'
SOUTH = 'South'
WEST = 'West'
PLAYERS = [NORTH, EAST, SOUTH, WEST]
NS_TEAM = (PLAYERS[0], PLAYERS[2])
EW_TEAM = (PLAYERS[1], PLAYERS[3])
TEAMS = (NS_TEAM, EW_TEAM)
TEAMMATES = {
    NORTH: SOUTH,
    EAST: WEST,
    SOUTH: NORTH,
    WEST: EAST
}